import { BaseEntity } from '../base/base.entity';
import { Location } from '../location/location.entity';
import { User } from '../users/user.entity';
import { Amenity } from './amenity.entity';
import { StudioAddOn } from './studio.addon.entity';
import { STUDIO_STATUS } from './studio.status';
export declare class Studio extends BaseEntity {
    name: string;
    status: STUDIO_STATUS;
    rejected_reason: string;
    description: string;
    rules: string[];
    price: number;
    capacity: number;
    isLive: boolean;
    depositRequired: boolean;
    studioLocation: string;
    addOns: StudioAddOn[];
    amenities: Amenity[];
    location: Location | null;
    genres: string[];
    artistLevels: string[];
    studioOpen: Date | string;
    studioClose: Date | string;
    userId: string;
    user: User;
    hardware: string[];
    software: string[];
    minSessionLength: number;
}
