import { Appointment } from '../appointment/appointment.entity';
import { Location } from '../location/location.entity';
import { Review } from '../review/review.entity';
import { Amenity } from '../studio/amenity.entity';
import { StudioRegistrationDto } from '../studio/dto/studio.registration.dto';
import { StudioAddOn } from '../studio/studio.addon.entity';
import { Studio } from '../studio/studio.entity';
import { User } from '../users/user.entity';
export declare const studioPicA = "https://images.unsplash.com/photo-1551710029-607e06bd45ff?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1351&q=80";
export declare const studioPicB = "https://images.unsplash.com/photo-1563330232-57114bb0823c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80";
export declare const studioPicC = "https://images.unsplash.com/photo-1535406208535-1429839cfd13?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1355&q=80";
export declare const studioPics: string[];
export declare function generateReview(studio: Studio, user: User): Review;
export declare function generateAmenities(): Amenity[];
export declare function generateAddOns(studioId: string, count?: number): StudioAddOn[];
export declare function generateLocation(): Location;
export declare function generateUser(): User;
export declare function generateStudio(user?: User): Studio;
export declare function generateAppointment(user: any, studio: any): Appointment;
export declare function generateStudioRegistration(user?: User): StudioRegistrationDto;
